// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where to store the authorization credentials.
 * Passed as the third argument to the `auth` command (0 = KV, 1 = OTP).
 * `None` / `Kv` is the default and preserves existing behavior.
 * OTP writes are irreversible — the UI must warn the user before selecting it.
 */
export type AuthStorage = "kv" | "otp";
