// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mirrors Python `FlashArgv.mode` (write / read); extended for GUI tabs.
 */
export type FlashMode = "flash" | "erase" | "read" | "authorize";
