import type { App } from 'vue';
import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import {
  faArrowDown,
  faArrowsRotate,
  faArrowUpRightFromSquare,
  faCheck,
  faChevronDown,
  faChevronRight,
  faChevronUp,
  faCircle,
  faCircleArrowUp,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faCircleXmark,
  faClock,
  faClockRotateLeft,
  faCopy,
  faDownload,
  faExpand,
  faFolderOpen,
  faGear,
  faKey,
  faMagnifyingGlass,
  faMagnifyingGlassMinus,
  faMagnifyingGlassPlus,
  faMicrochip,
  faPlug,
  faPlugCircleXmark,
  faPlus,
  faPowerOff,
  faRotate,
  faScroll,
  faTag,
  faToolbox,
  faTrash,
  faTrashCan,
  faTriangleExclamation,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faArrowDown,
  faArrowsRotate,
  faArrowUpRightFromSquare,
  faCheck,
  faChevronDown,
  faChevronRight,
  faChevronUp,
  faCircle,
  faCircleArrowUp,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faCircleXmark,
  faClock,
  faClockRotateLeft,
  faCopy,
  faDownload,
  faExpand,
  faFolderOpen,
  faGear,
  faKey,
  faMagnifyingGlass,
  faMagnifyingGlassMinus,
  faMagnifyingGlassPlus,
  faMicrochip,
  faPlug,
  faPlugCircleXmark,
  faPlus,
  faPowerOff,
  faRotate,
  faScroll,
  faTag,
  faToolbox,
  faTrash,
  faTrashCan,
  faTriangleExclamation,
  faXmark,
);

export function registerFontAwesome(app: App): void {
  app.component('FontAwesomeIcon', FontAwesomeIcon);
}
