name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Make build script executable
        run: chmod +x ./tools/build_package.sh

      - name: Build package
        run: ./tools/build_package.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-artifacts
          path: |
            dist/tyutool_cli.tar.gz
            dist/tyutool_gui.tar.gz
            dist/ideserial.json
            dist/upgrade_config.json

  build-macos-x86:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Make build script executable
        run: chmod +x ./tools/build_package.sh

      - name: Build package
        run: ./tools/build_package.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-x86-artifacts
          path: |
            dist/darwin_x86_tyutool_cli.tar.gz
            dist/darwin_x86_tyutool_gui.tar.gz

  build-macos-arm:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Make build script executable
        run: chmod +x ./tools/build_package.sh

      - name: Build package
        run: ./tools/build_package.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-arm-artifacts
          path: |
            dist/darwin_arm64_tyutool_cli.tar.gz
            dist/darwin_arm64_tyutool_gui.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos-x86, build-macos-arm]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/linux-artifacts/*
            artifacts/macos-x86-artifacts/*
            artifacts/macos-arm-artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
